# Generated by Django 4.2.21 on 2025-05-24 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('wish', 'Пожелание'), ('problem', 'Проблема'), ('complaint', 'Претензия'), ('other', 'Другое')], max_length=20, verbose_name='Тип обращения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Прикрепленный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
